### PR TITLE
Polymer 3 2018 11 29 103955

### PR DESCRIPTION
**Pull request by awikkerink**
Used the toPolymer.sh script mostly to convert the test html files

I'm using a `prepare` script to handle the commonjs stuff from `frau-jwt`. I took a quick look at it's dependencies and it doesn't look like it would that much work to move to es6. The only major change would be to use the fetch API. I don't know how to get it working for node as well though...

### CODE REVIEW

**Comment by awikkerink** [comment]
@dlockhart do you think this could be added to the npm registry like d2l-hypermedia-constants or do you think a CI build adding the `dist` and `es6` directories would be appropriate?

**Comment by dlockhart** [comment]
I think this (and the other `d2l-fetch-*` friends) could definitely live on NPM. We just haven't been putting the components themselves there yet because we weren't sure if we'd be doing a monorepo for them.

**Comment by awikkerink** [comment]
Who would I ask to get the d2l-travis-deploy creds?

**Comment by awikkerink** [comment]
ping @dlockhart @CodeBaboon @ryantmer

**Pull request merged**
